dado = str(input('Digite algo: '))
print(type(dado))
print('É AlfaNumérico? ',dado.isalnum())
print('É Alfa? ',dado.isalpha())
print('É Numerico? ',dado.isnumeric())
print('É Space? ',dado.isspace())
print('É Caixa alta? ',dado.isupper())
print('E Caixa baixa? ',dado.islower())
print('É capitalizada? ',dado.istitle())
